- packages/xflow-docs/docs/tutorial/solutions/flow/demos/config-menu.ts
- packages/xflow-docs/docs/tutorial/solutions/flow/index.md
> docs: 补充流程图组件文档

- packages/xflow-extension/src/flowchart-canvas/extension/components/index.tsx
- packages/xflow-extension/src/flowchart-canvas/index.tsx
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/canvas.tsx
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/edge.tsx
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/group.tsx
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/node.tsx
- packages/xflow-extension/src/flowchart-editor-panel/form-panel.tsx
- packages/xflow-extension/src/flowchart-node-panel/group-panel/group.tsx
- packages/xflow-extension/src/flowchart-node-panel/index.tsx
- packages/xflow-extension/src/flowchart-node-panel/style/index.ts
> fix: remove less style

- .eslintrc.js
- package.json
- packages/xflow-core/.eslintrc.js
- packages/xflow-core/package.json
- packages/xflow-core/src/common/rx-model-hook.tsx
- packages/xflow-core/src/model-service/utils.tsx
- packages/xflow-docs/.umirc.ts
- packages/xflow-docs/docs/index.zh-CN.md
- packages/xflow-docs/docs/index.zh.md
- packages/xflow-docs/package.json
- packages/xflow-extension/.eslintrc.js
- packages/xflow-extension/package.json
- packages/xflow-extension/src/flowchart-canvas/utils/util.ts
- packages/xflow-extension/src/flowchart-editor-panel/form-wrapper.tsx
- packages/xflow-extension/src/flowchart-editor-panel/useAsync.ts
- packages/xflow-hook/package.json
- packages/xflow/package.json
fix: remove unnecessary hook deps to avoid endlesss loop
> fix: remove unnecessary hook deps to avoid endlesss loop

- package.json
- packages/xflow-core/package.json
- packages/xflow-core/src/command-contributions/components/context.tsx
- packages/xflow-core/src/interface.ts
- packages/xflow-core/src/menu/interface.ts
- packages/xflow-core/src/xflow-main/graph/config.ts
- packages/xflow-docs/.umirc.ts
- packages/xflow-docs/docs/api/models/index.md
- packages/xflow-docs/docs/tutorial/extension-components/canvas-node-panel/demos/custom/comannd-utils.tsx
- packages/xflow-docs/docs/tutorial/extension-components/canvas-node-panel/demos/custom/dnd-tree-config.tsx
- packages/xflow-docs/docs/tutorial/extension-components/canvas-node-panel/demos/custom/graph-config.tsx
- packages/xflow-docs/docs/tutorial/extension-components/canvas-node-panel/demos/custom/index.less
- packages/xflow-docs/docs/tutorial/extension-components/canvas-node-panel/demos/custom/index.tsx
- packages/xflow-docs/docs/tutorial/extension-components/canvas-node-panel/demos/custom/mock.ts
- packages/xflow-docs/docs/tutorial/extension-components/canvas-node-panel/demos/search/index.less
- packages/xflow-docs/docs/tutorial/extension-components/canvas-node-panel/index.md
- packages/xflow-docs/package.json
- packages/xflow-extension/package.json
- packages/xflow-extension/src/canvas-node-tree-panel/interface.tsx
- packages/xflow-extension/src/canvas-node-tree-panel/panel-body.tsx
- packages/xflow-extension/src/flowchart-node-panel/panel-body.tsx
- packages/xflow-hook/package.json
- packages/xflow/package.json
nodeTreeService support render custom node Component besides renderKey
```
/** tree node model */
export interface ITreeNode {
/**
* 支持自定义渲染
*/
render?: React.ComponentType<{ data: ITreeNode; isNodeTreePanel: boolean }>
}
```
if the tree node renders diff from the graph, it needs a custom render.
for example: 
if a product requires a node panel to render text which can drag and drop text on the graph.  after the user drags text and drops it on the graph, it will render a rectangle node on the graph. 
- [] Docs (changes that only update documentation)
> feat: canvas node panel support custom render 

- package.json
- packages/xflow-core/package.json
- packages/xflow-docs/package.json
- packages/xflow-extension/package.json
- packages/xflow-hook/package.json
- packages/xflow/package.json
fix: upgrade antv/layout version
> fix: upgrade antv/layout version

- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/fields/color.tsx
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/style.less
#24 https://github.com/antvis/XFlow/issues/24
> fix: 修复color-picker render 产生的 warning

- packages/xflow-extension/src/flowchart-canvas/config-graph.tsx
> fix: 修改临时边名称避免和demo冲突

- README.MD
- packages/xflow-docs/docs/tutorial/extension-components/canvas-config-form/demos/deps/graph-config.tsx
- packages/xflow-docs/docs/tutorial/extension-components/canvas-config-form/demos/deps/index.less
- packages/xflow-docs/docs/tutorial/extension-components/canvas-config-form/demos/deps/index.tsx
- packages/xflow-docs/docs/tutorial/extension-components/canvas-config-form/demos/deps/mock.ts
- packages/xflow-docs/docs/tutorial/extension-components/canvas-config-form/demos/rules/graph-config.tsx
- packages/xflow-docs/docs/tutorial/extension-components/canvas-config-form/demos/rules/index.less
- packages/xflow-docs/docs/tutorial/extension-components/canvas-config-form/demos/rules/index.tsx
- packages/xflow-docs/docs/tutorial/extension-components/canvas-config-form/demos/rules/mock.ts
- packages/xflow-docs/docs/tutorial/extension-components/canvas-config-form/index.md
- packages/xflow-extension/src/canvas-json-schema-form/interface.tsx
- packages/xflow-extension/src/canvas-json-schema-form/schema-form/control-map/checkbox/index.tsx
- packages/xflow-extension/src/canvas-json-schema-form/schema-form/control-map/datetime/index.tsx
- packages/xflow-extension/src/canvas-json-schema-form/schema-form/control-map/float/index.tsx
- packages/xflow-extension/src/canvas-json-schema-form/schema-form/control-map/select/index.tsx
- packages/xflow-extension/src/canvas-json-schema-form/schema-form/control-map/string-input/index.tsx
- packages/xflow-extension/src/canvas-json-schema-form/schema-form/control-map/text-area/index.tsx
add demo:
1. form item dependencies demo 
2. form item rule demo
> docs: add form demo

- packages/xflow-extension/src/flowchart-canvas/utils/events.ts
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/fields/color.tsx
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/style.less
- 使用 createPortal 避免层级遮挡
- 优化 movedNode 判断逻辑，仅需更新边
> feat:  使用 createPortal

- packages/xflow-core/package.json
- packages/xflow-core/src/command-contributions/cmd-context.ts
- packages/xflow-core/src/command-contributions/graph/graph-load-data.ts
- packages/xflow-core/src/command-contributions/graph/graph-meta.ts
- packages/xflow-core/src/command-contributions/graph/graph-render.ts
- packages/xflow-core/src/command-contributions/graph/graph-save-data.ts
- packages/xflow-core/src/command/interface.ts
- packages/xflow-core/src/interface.ts
- packages/xflow-core/src/model-service/constant.ts
- packages/xflow-docs/package.json
- packages/xflow-extension/package.json
- packages/xflow-extension/src/canvas-node-tree-panel/service.tsx
- packages/xflow-hook/package.json
- packages/xflow/package.json
fix graph meta undefined issue
> fix graph meta undefined issue

- packages/xflow-core/package.json
- packages/xflow-docs/package.json
- packages/xflow-extension/package.json
- packages/xflow-hook/package.json
- packages/xflow/package.json
fix: prototype pollution in immer Close:#30
> fix: prototype pollution in immer Close:#30

- packages/xflow-docs/docs/api/commands/graph/graph-layout/demos/index.less
- packages/xflow-docs/docs/api/commands/graph/graph-layout/demos/index.tsx
- packages/xflow-docs/docs/api/commands/graph/graph-meta/index.md
- packages/xflow-docs/docs/api/commands/graph/graph-render/demos/index.less
- packages/xflow-docs/docs/api/commands/graph/graph-render/demos/index.tsx
- packages/xflow-docs/docs/api/commands/graph/graph-zoom/demos/index.less
- packages/xflow-docs/docs/api/commands/graph/graph-zoom/demos/index.tsx
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/basic/config-graph.tsx
> fix api demo height issue

- packages/xflow-core/package.json
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/basic/config-graph.tsx
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/basic/index.less
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/basic/react-node/algo-node.less
- packages/xflow-docs/package.json
- packages/xflow-extension/package.json
- packages/xflow-hook/package.json
- packages/xflow/package.json
docs: fix dag demo style issue
> docs: fix dag demo style issue

- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/fields/select.tsx
fix type error
```
packages/xflow-extension prepare: ./src/index.tsx → dist/index.umd.js...
Error: packages/xflow-extension prepare: src/flowchart-editor-panel/control-map-service/components/fields/select.tsx(36,28): error TS2339: Property 'toLowerCase' does not exist on type 'Omit<DefaultOptionType, "children">[]'.
```
> fix: flow form control type error

- .changeset/olive-ties-camp.md
- .changeset/soft-rules-shake.md
- .github/workflows/release.yml
- package.json
- packages/xflow-core/src/hooks/contributions/graph.ts
- packages/xflow-core/src/hooks/interface.ts
- packages/xflow-core/src/index.tsx
- packages/xflow-core/src/xflow-main/components/index.tsx
- packages/xflow-core/src/xflow-main/graph/graph-provider.tsx
- packages/xflow-core/src/xflow-main/index.tsx
- packages/xflow-docs/docs/api/hooks/index.md
- packages/xflow-docs/docs/api/interface/application.md
- packages/xflow-docs/docs/tutorial/advanced/hook/index.md
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/basic/cmd-extensions/cmd-rename-node-modal.tsx
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/port-config/cmd-extensions/cmd-rename-node-modal.tsx
- packages/xflow/src/core/index.ts
> By fix/destroy spelling

- package.json
fix: publish script escape git branch check
> fix: publish script

- .changeset/large-clouds-allow.md
- .changeset/polite-stingrays-yawn.md
- packages/xflow-core/src/command-contributions/edge/edge-add.ts
- packages/xflow-core/src/command-contributions/edge/edge-del.ts
- packages/xflow-core/src/command-contributions/node/node-add.ts
- packages/xflow-core/src/command-contributions/node/node-del.ts
support model options in add/del node/edge command Close #68
> feat: support model options in add/del node/edge command Close#68

- .changeset/large-clouds-allow.md
- .changeset/polite-stingrays-yawn.md
- packages/xflow-core/src/command-contributions/edge/edge-add.ts
- packages/xflow-core/src/command-contributions/edge/edge-del.ts
- packages/xflow-core/src/command-contributions/edge/edge-update.ts
- packages/xflow-core/src/command-contributions/node/node-add.ts
- packages/xflow-core/src/command-contributions/node/node-del.ts
support model options in add/del node/edge command Close #68
> support model options in add/del node/edge command Close #68

- .changeset/emighty-sloths-do.md
- packages/xflow-core/src/command-contributions/graph/graph-meta.ts
> fix: in addition to support set any key in graph meta including 'flowId'

- .changeset/cuddly-foxes-dream.md
- packages/xflow-core/src/index.tsx
- packages/xflow-core/src/xflow-main/index.tsx
- packages/xflow-extension/src/flowchart-canvas/config-graph.tsx
- packages/xflow-extension/src/flowchart-canvas/interface.ts
- 新增 useConfig 配置，支持 createGraphConfig 回调
- setX6Config 使用 merge 
- 修复类型定义
> feat: 新增 useConfig 配置

- .changeset/green-dots-suffer.md
- .changeset/serious-rocks-walk.md
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/layout/config-graph.tsx
- packages/xflow-extension/src/canvas-dag-extension/contributions/dag.tsx
>  fix: dag extension connecting edge support right to left layout

- .changeset/fast-buckets-push.md
- packages/xflow-core/src/command-contributions/node/node-update.ts
> fix: node update command error

- .changeset/calm-adults-decide.md
- packages/xflow-extension/src/flowchart-canvas/config-graph.tsx
fix: flow chart cannot trigger addEdgeService
> fix: flow chart cannot trigger addEdgeService

- .changeset/calm-adults-decide.md
- .changeset/sour-carpets-cheat.md
- examples/quick-start-cra/package.json
- examples/quick-start-cra/src/index.less
- examples/quick-start-cra/src/index.tsx
- examples/quick-start-cra/tsconfig.json
- examples/quick-start-umi/package.json
- examples/quick-start-umi/src/pages/index.tsx
- packages/xflow-core/package.json
- packages/xflow-docs/docs/tutorial/extension-components/canvas-config-form/demos/custom-render/index.tsx
- packages/xflow-extension/src/canvas-json-schema-form/interface.tsx
> Fix: JsonSchemaForm type error

- .changeset/six-cameras-hear.md
- .changeset/violet-camels-juggle.md
- tsconfig.json
feat: enable importHelpers compile option
> feat: enable importHelpers compile option

- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/fields/color.tsx
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/fields/index.ts
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/index.ts
- packages/xflow-extension/src/flowchart-editor-panel/index.ts
- packages/xflow-extension/src/flowchart-editor-panel/interface.ts
- 导出 ColorPicker 等组件，方便上层组合使用
- 修复 getCustomRenderComponent 类型定义丢失
> feat: 类型&组件导出

- packages/xflow-docs/docs/tutorial/getting-started/index.zh.md
> Update index.zh.md fix some typo

- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/node-text.tsx
- packages/xflow-extension/src/flowchart-node-panel/constants.ts
> feat: 优化节点配置面板

- packages/xflow-core/src/command-contributions/constant.ts
- packages/xflow-core/src/command-contributions/graph/graph-fulllscreen.ts
- packages/xflow-core/src/command-contributions/graph/index.ts
- packages/xflow-core/src/model-service/constant.ts
- packages/xflow-core/src/model-service/contributions/graph-model.ts
- packages/xflow-core/src/xflow-main/components/extension-registry.tsx
- packages/xflow-core/src/xflow-main/components/index.tsx
- packages/xflow-core/src/xflow-main/graph/config.ts
- packages/xflow-docs/docs/tutorial/solutions/flow/demos/index.tsx
- packages/xflow-extension/src/canvas-scale-toolbar/config.tsx
- packages/xflow-extension/src/flowchart-canvas/interface.ts
- 新增全屏 comand 
||
|---|
|![image](https://user-images.githubusercontent.com/31396322/155709821-c4aa1762-7fb1-4855-bd62-6ed44e98f3e2.png)|
> feat: 新增 canvas scale 全屏功能

- packages/xflow-extension/src/flowchart-canvas/config-graph.tsx
- packages/xflow-extension/src/flowchart-canvas/extension/contributions/flow.tsx
https://github.com/ant-design/ant-design-charts/issues/1189
> fix: 修复新增边时节点关联边信息丢失

- packages/xflow-core/src/command-contributions/graph/graph-update.ts
- packages/xflow-extension/src/flowchart-canvas/config-graph.tsx
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/canvas.tsx
> feat: 支持配置画布背景颜色和图片

- .changeset/little-pens-drum.md
- packages/xflow-core/package.json
> chore: upgrade mana-common version Close#114

- .changeset/few-icons-draw.md
- .changeset/healthy-ladybugs-ring.md
- packages/xflow-core/src/command-contributions/edge/edge-update.ts
- packages/xflow-core/src/command-contributions/node/node-update.ts
fix: visible typo in node and edge's update command
> fix: typo in node and edge command visible update

- packages/xflow-docs/docs/tutorial/solutions/flow/demos/config-toolbar.ts
- packages/xflow-extension/src/canvas-toolbar/render-components/toolbar-item.tsx
> feat: 完善 toolbar 功能

- .changeset/late-socks-sing.md
- packages/xflow-core/src/command-contributions/graph/graph-render.ts
- packages/xflow-docs/docs/tutorial/solutions/er/demos/index.less
> feat: fix graphrender command can't update node

- .changeset/fluffy-files-refuse.md
> chore: release verison

- packages/xflow-extension/src/canvas-json-schema-form/interface.tsx
- packages/xflow-extension/src/canvas-json-schema-form/service.tsx
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/node-text.tsx
- packages/xflow-extension/src/flowchart-editor-panel/form-panel.tsx
- packages/xflow-extension/src/flowchart-editor-panel/form-schema-service/index.ts
- packages/xflow-extension/src/flowchart-editor-panel/form-wrapper.tsx
- packages/xflow-extension/src/flowchart-editor-panel/interface.ts
- packages/xflow-extension/src/flowchart-node-panel/constants.ts
- packages/xflow-extension/src/flowchart-node-panel/group-panel/group.less
- packages/xflow-extension/src/flowchart-node-panel/group-panel/group.tsx
- packages/xflow-extension/src/flowchart-node-panel/node-components.tsx
- packages/xflow-extension/src/flowchart-node-panel/style/index.less
> Multi select

- .changeset/wet-forks-raise.md
- packages/xflow-core/src/command-contributions/graph/graph-render.ts
fix  https://github.com/antvis/XFlow/issues/174
> fix: graph-render command order

- .changeset/little-queens-report.md
- packages/xflow-core/package.json
fix release issue:https://github.com/antvis/XFlow/pull/194
deprecate version @antv/xflow-core@2.0.0
> fix release issue

- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/index.ts
- packages/xflow-extension/src/index.tsx
> feat: 内置组件导出

- packages/xflow-core/src/command-contributions/graph/graph-fulllscreen.ts
- packages/xflow-core/src/model-service/contributions/graph-model.ts
- packages/xflow-extension/src/canvas-node-tree-panel/panel-body.tsx
- 修复 esc 退出全屏后 model 不更新的 bug
- 修复全屏状态下节点 popover 不显示的 bug
> fix: 修复全屏 bug

- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/fields/index.ts
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/fields/position.tsx
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/fields/size.tsx
- packages/xflow/src/extensions/index.ts
> fix: 流程图原子组件导出

- packages/xflow-docs/docs/tutorial/solutions/flow/demos/index.tsx
- packages/xflow-extension/src/flowchart-node-panel/constants.ts
- packages/xflow-extension/src/flowchart-node-panel/node-components.tsx
- packages/xflow-extension/src/flowchart-node-panel/panel-footer.tsx
- packages/xflow-extension/src/flowchart-node-panel/paths/card/index.tsx
- packages/xflow-extension/src/flowchart-node-panel/style/index.less
> feat: 调整左侧节点面板样式

- packages/xflow-core/src/command-contributions/graph/graph-save-data.ts
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/edge-text.tsx
- packages/xflow-extension/src/flowchart-node-panel/index.tsx
- packages/xflow-extension/src/flowchart-node-panel/interface.tsx
- packages/xflow-extension/src/flowchart-node-panel/node-components.tsx
- packages/xflow-extension/src/flowchart-node-panel/panel-footer.tsx
- packages/xflow-extension/src/flowchart-toolbar/utils.tsx
> feat: 支持保存流程图数据

- .changeset/dirty-meals-check.md
- packages/xflow-extension/src/canvas-scale-toolbar/config.tsx
> fix: 修复全屏导致的GRAPH_SCALE无法更新

- .changeset/shy-phones-report.md
- packages/xflow-core/src/command-contributions/edge/edge-del.ts
> fix:  Type of source & target in edgeConfig

- packages/xflow-extension/src/canvas-json-schema-form/service.tsx
- packages/xflow-extension/src/flowchart-node-panel/group-panel/group.tsx
- packages/xflow-extension/src/index.tsx
- packages/xflow/src/extensions/index.ts
> fix: 修复 ts 错误

- README.md
- README.zh-CN.md
- packages/xflow-docs/docs/tutorial/getting-started/index.en-US.md
- packages/xflow-docs/docs/tutorial/getting-started/index.zh-CN.md
- packages/xflow-docs/docs/tutorial/getting-started/index.zh.md
> docs: fix typo

- packages/xflow-core/src/command-contributions/graph/graph-save-data.ts
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/basic/config-cmd.ts
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/dynamic-ports/config-cmd.ts
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/layout/config-cmd.ts
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/port-config/config-cmd.ts
> fix: 修复 save hook 拼写

- packages/xflow-core/src/command-contributions/node/node-update.ts
> fix: 修复更新节点的旋转角度无效 (#242)

- .changeset/giant-donkeys-look.md
- packages/xflow-extension/src/flowchart-node-panel/style/index.less
- packages/xflow-extension/src/flowchart-node-panel/utils.tsx
- fix: 修复自定义节点注册失败
- feat: 调整内置节点样式
> fix: 修复自定义节点注册失败

- .changeset/little-queens-report.md
- .changeset/mighty-peaches-juggle.md
- packages/xflow-core/package.json
- packages/xflow-extension/package.json
- packages/xflow-hook/package.json
> chore  release version

- .changeset/selfish-papayas-agree.md
- packages/xflow-core/src/command-contributions/graph/graph-render.ts
- packages/xflow-docs/docs/tutorial/solutions/dag/demos/dynamic-ports/config-graph.tsx
> fix: add render graph options to avoid dupilcated port 

- .changeset/fuzzy-trains-wink.md
- .changeset/quick-shrimps-listen.md
- .changeset/tasty-flies-rhyme.md
- packages/xflow-core/src/interface.ts
- packages/xflow-core/src/menu/interface.ts
- packages/xflow-core/src/toolbar/interface.ts
- packages/xflow-extension/package.json
- packages/xflow-extension/src/canvas-collapse-panel/service.tsx
- packages/xflow-extension/src/canvas-context-menu/components/menu.tsx
- packages/xflow-extension/src/canvas-json-schema-form/service.tsx
- packages/xflow-extension/src/flowchart-node-panel/service.tsx
- packages/xflow-extension/src/flowchart-node-panel/utils.tsx
> chore: release version

- .changeset/cool-queens-applaud.md
- packages/xflow-core/src/command-contributions/node/node-update.ts
> fix: 修复更新节点命令(UpdateNode command)中对旋转角度的处理，导致角度不正确的问题 (#265)

- .changeset/swift-bottles-type.md
- packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/fields/color.tsx
- packages/xflow-extension/src/flowchart-node-panel/style/index.less
> fix: 修复 color 选择器全屏时被遮挡

- .changeset/twenty-owls-collect.md
- packages/xflow-extension/src/flowchart-canvas/config-graph.tsx
- packages/xflow-extension/src/flowchart-canvas/extension/contributions/flow.tsx
- packages/xflow-extension/src/flowchart-canvas/interface.ts
- packages/xflow-extension/src/flowchart-canvas/utils/events.ts
- feat: 流程图新增连线默认样式配置
- feat: 新增鼠标交互，节点选中时仍然可以开启hover进行连线
> feat: 新增 edgeConfig 和 showPortOnNodeSelected

- .changeset/quick-birds-appear.md
- packages/xflow-extension/src/flowchart-canvas/config-graph.tsx
isFunction => typeof x === 'function'
> fix: 修复 isFunction action 类型检测错误

- .changeset/tricky-poets-sing.md
- packages/xflow-core/package.json
- packages/xflow-docs/package.json
- packages/xflow-extension/package.json
- packages/xflow-hook/package.json
- packages/xflow/package.json
> chore: release latest version

- .changeset/thirty-owls-rest.md
- packages/xflow-core/src/command-contributions/mapping-service.ts
fix: copy edge cannot find portid CLOSE:#322
> fix: copy edge cannot find portid CLOSE:#322

- .changeset/strong-steaks-relax.md
> chore: 版本发布

- .gitignore
- packages/xflow-core/src/command-contributions/graph/graph-copy.ts
- packages/xflow-core/src/command-contributions/graph/graph-paste.ts
- packages/xflow-core/src/command-contributions/mapping-service.ts
- packages/xflow-core/src/interface.ts
修复开启**群组**后, 无法复制/粘贴群组里面的**连接线**, 目前发现有三个问题
> 复现地址: https://xflow.antv.vision/docs/tutorial/solutions/flow
- `复制`: `getSelectedCells` 里面不包含 `edges`, 按照[官网的介绍](https://x6.antv.vision/zh/docs/tutorial/basic/cell) 连接线也属于 `edges`, 但是却拿不到
不知道是我理解有误, 还是 XFlow 依赖的 X6 对应版本有 bug, 所以修改为 `getSelectedCells` + `getEdges` 组合的方式 (我看 `parseCells` 已经有相应 edges 过滤的处理) 保证复制到正确的东西
- `粘贴`: 断点看下来, 复制拿到的 `source` 和 `target` 并不是类型定义的 `string`, 而是 `{ port: string, cell: string }`, 而 `nodeMappingRecord` 的 key 又是 `string`, 导致始终无法拿到需要粘贴 `edges`, 然后拿到的配置又是透传给 `X6`, 里面包含原 edge 的 `id`, 又会导致无法渲染
- `空节点`: 空节点没有 `label` 的时候也会拼一个 `xx_copied` 的名称, 感觉有点奇怪, 不知道是故意的还是啥
能力有限, 只能定位到这里的, **不确定这样修改会不会碰伤其他逻辑**, 也没看到有任何的单测, 如果这个库还要维护的话, 请大佬 review 一下, 或者给出更好的解决方式
|  修复前 |  修复后 |
|  -  |  - |
| ![Kapture 2023-02-23 at 15 18 …
> fix(flow-chart): fix cannot copy/paste edges within group

- .changeset/spicy-moose-jam.md
- .changeset/strong-steaks-relax.md
- .changeset/tidy-ways-cough.md
- packages/xflow-core/package.json
- packages/xflow-core/src/command-contributions/graph/graph-paste.ts
- packages/xflow-core/src/command-contributions/mapping-service.ts
- packages/xflow-core/src/common/graph-utils.ts
- packages/xflow-core/src/interface.ts
- packages/xflow-docs/package.json
- packages/xflow-extension/package.json
- packages/xflow-hook/package.json
- packages/xflow/package.json
fix PR#335
https://github.com/antvis/XFlow/pull/355
> fix: cannot paste group in flowchart

- packages/xflow/package.json
> Add missing repo info

- apps/basic/src/pages/dag/config-drawer/index.tsx
- apps/basic/src/pages/dag/node.less
- apps/basic/src/pages/dag/shape.tsx
- apps/basic/src/pages/dag/toolbar/index.tsx
> feat: add node dropDown

- packages/core/src/util/object.ts
> fix(core): Cannot read properties of null (reading hasOwnProperty)

- apps/basic/src/pages/group/GroupNode/index.tsx
- apps/basic/src/pages/group/NormalNode/index.tsx
- apps/basic/src/pages/group/index.tsx
- apps/basic/src/pages/group/tools.tsx
- packages/core/package.json
- packages/core/src/components/Background.tsx
- packages/core/src/components/Clipboard.tsx
- packages/core/src/components/Control.tsx
- packages/core/src/components/Graph.tsx
- packages/core/src/components/Grid.tsx
- packages/core/src/components/History.tsx
- packages/core/src/components/Minimap.tsx
- packages/core/src/components/Snapline.tsx
- packages/core/src/components/State.tsx
- packages/core/src/components/Transform.tsx
- packages/core/src/components/Wrapper.tsx
- packages/core/src/components/XFlow.tsx
- packages/core/src/context/GraphContext.tsx
- packages/core/src/context/StoreContext.tsx
- packages/diff/package.json
- packages/diff/src/components/DiffGraph/index.tsx
- packages/diff/src/components/DiffGraph/tool.tsx
- packages/diff/tsconfig.json
- pnpm-lock.yaml
- tooling/tsconfig/tsconfig.json
> feat: support react lowest version 16.8.6
